<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>SafeFreeSpace</AssemblyName>
    <RootNamespace>SafeFreeSpace.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SafeFreeSpace.Contracts\SafeFreeSpace.Contracts.csproj" />
    <ProjectReference Include="..\SafeFreeSpace.Core\SafeFreeSpace.Core.csproj" />
    <ProjectReference Include="..\SafeFreeSpace.Infrastructure.Windows\SafeFreeSpace.Infrastructure.Windows.csproj" />
  </ItemGroup>
</Project>
